services:
  - type: web
    name: mern-ecommerce
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
